# Generated by Django 4.0 on 2021-12-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('dob', models.DateField()),
                ('photo', models.CharField(max_length=254)),
                ('strava_id', models.BigIntegerField()),
                ('strava_access_token', models.CharField(max_length=1024)),
                ('strava_refresh_token', models.CharField(max_length=1024)),
                ('strava_expires_at', models.FloatField()),
                ('strava_reauth_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('distance', models.IntegerField()),
                ('distance_unit', models.CharField(choices=[('M', 'Miles'), ('K', 'Kilometres')], max_length=1)),
                ('strava_segment_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('evidence', models.CharField(max_length=1024)),
                ('strava_activity_id', models.BigIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.athlete')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.race')),
            ],
        ),
    ]
