# Generated by Django 4.0 on 2021-12-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='evidence',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='Profile Photo URL'),
        ),
    ]
