# Generated by Django 4.0 on 2021-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(default='5k Road Race', max_length=254),
            preserve_default=False,
        ),
    ]
