# Generated by Django 4.0 on 2021-12-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="age_grade",
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
    ]
