# Generated by Django 4.0 on 2021-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_race_submissions_close"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="distance",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
