# Generated by Django 4.0 on 2021-12-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_race_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="route_gpx",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="race",
            name="route_image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
