# Generated by Django 4.0.5 on 2022-06-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_race_parent_race_race_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='match_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='parent_race',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'RELAY_PARENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.race'),
        ),
    ]
