# Generated by Django 4.0 on 2021-12-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('sex', models.CharField(max_length=1)),
                ('photo', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StravaAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('expires_at', models.FloatField()),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.athlete')),
            ],
        ),
    ]
